### ISSUE TITLE
STM32G0

### ISSUE THREAD

**Issue by comato** [nimaltd/EEPROM#4]
Nice library... How to use it on STM32G0?

**Comment by nimaltd** [comment]
Hello. I did not test on G series. But I think work.

**Comment by comato** [comment]
I tried it with STM32G030 (32KB flash) But in HAL are some differencies,
FLASH_TYPEPROGRAM_WORD is changed to FLASH_TYPEPROGRAM_DOUBLEWORD
flashErase.PageAddress is changed to flashErase.Page
Also I am not sure what is page size (2048 bytes?)

**Comment by comato** [comment]
it is working, to flashErase.Page is needed to write page number, not addres. Also I changed all /4 *4 to /8 *8 because DOUBLEWORD ...

**Comment by leech001** [comment]
> it is working, to flashErase.Page is needed to write page number, not addres. Also I changed all /4 *4 to /8 *8 because DOUBLEWORD ...

Hi. Can you share your config for STM32G030F6P6?

**Comment by leech001** [comment]
Added ability to work with STM32G030xx series #18
