### ISSUE TITLE
Can you help me use these files in Arduino IDE?

### ISSUE THREAD

**Issue by Joypacharya** [nimaltd/EEPROM#6]
Hello!!!
These files are really helpful for store data into Flash memory which works as EEPROM.
But my question regarding how to deploy these files into my Arduino IDE means using with ref. library in my ide and store data in it.
I know how to add the files but I want to add these files and run my code based on Arduino 32Core selection. I hope you really help me.

**Comment by nimaltd** [comment]
this library only work on stm32 platform. you should find another arduino library

**Comment by Joypacharya** [comment]
I am using the stm32f103c8 controller and select the STM32 Core for programming.
I hope now you can help me.

**Comment by nimaltd** [comment]
This library for HAL, not arduino. I'm sorry
